/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysenRouteImport } from './routes/analysen'
import { Route as AthletiktrainingRouteImport } from './routes/athletiktraining'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as GruppentrainingRouteImport } from './routes/gruppentraining'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as MeinePersonRouteImport } from './routes/meine-person'
import { Route as PerformanceClubRouteImport } from './routes/performance-club'
import { Route as PersonaltrainingRouteImport } from './routes/personaltraining'
import { Route as PhysiotherapieRouteImport } from './routes/physiotherapie'
import { Route as StartRouteImport } from './routes/start'
import { Route as StrengthClubRouteImport } from './routes/strength-club'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TrainingClubWidnauRouteImport } from './routes/training-club-widnau'
import { Route as TrainingPhysioRouteImport } from './routes/training-physio'
import { Route as TrainingstherapieRouteImport } from './routes/trainingstherapie'
import { Route as VortraegeRouteImport } from './routes/vortraege'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysenRoute = AnalysenRouteImport.update({
  id: '/analysen',
  path: '/analysen',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletiktrainingRoute = AthletiktrainingRouteImport.update({
  id: '/athletiktraining',
  path: '/athletiktraining',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const GruppentrainingRoute = GruppentrainingRouteImport.update({
  id: '/gruppentraining',
  path: '/gruppentraining',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const MeinePersonRoute = MeinePersonRouteImport.update({
  id: '/meine-person',
  path: '/meine-person',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceClubRoute = PerformanceClubRouteImport.update({
  id: '/performance-club',
  path: '/performance-club',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaltrainingRoute = PersonaltrainingRouteImport.update({
  id: '/personaltraining',
  path: '/personaltraining',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysiotherapieRoute = PhysiotherapieRouteImport.update({
  id: '/physiotherapie',
  path: '/physiotherapie',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const StrengthClubRoute = StrengthClubRouteImport.update({
  id: '/strength-club',
  path: '/strength-club',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingClubWidnauRoute = TrainingClubWidnauRouteImport.update({
  id: '/training-club-widnau',
  path: '/training-club-widnau',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingPhysioRoute = TrainingPhysioRouteImport.update({
  id: '/training-physio',
  path: '/training-physio',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingstherapieRoute = TrainingstherapieRouteImport.update({
  id: '/trainingstherapie',
  path: '/trainingstherapie',
  getParentRoute: () => rootRouteImport,
} as any)
const VortraegeRoute = VortraegeRouteImport.update({
  id: '/vortraege',
  path: '/vortraege',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysen': typeof AnalysenRoute
  '/athletiktraining': typeof AthletiktrainingRoute
  '/clubs': typeof ClubsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gruppentraining': typeof GruppentrainingRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/meine-person': typeof MeinePersonRoute
  '/performance-club': typeof PerformanceClubRoute
  '/personaltraining': typeof PersonaltrainingRoute
  '/physiotherapie': typeof PhysiotherapieRoute
  '/start': typeof StartRoute
  '/strength-club': typeof StrengthClubRoute
  '/team': typeof TeamRoute
  '/training-club-widnau': typeof TrainingClubWidnauRoute
  '/training-physio': typeof TrainingPhysioRoute
  '/trainingstherapie': typeof TrainingstherapieRoute
  '/vortraege': typeof VortraegeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysen': typeof AnalysenRoute
  '/athletiktraining': typeof AthletiktrainingRoute
  '/clubs': typeof ClubsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gruppentraining': typeof GruppentrainingRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/meine-person': typeof MeinePersonRoute
  '/performance-club': typeof PerformanceClubRoute
  '/personaltraining': typeof PersonaltrainingRoute
  '/physiotherapie': typeof PhysiotherapieRoute
  '/start': typeof StartRoute
  '/strength-club': typeof StrengthClubRoute
  '/team': typeof TeamRoute
  '/training-club-widnau': typeof TrainingClubWidnauRoute
  '/training-physio': typeof TrainingPhysioRoute
  '/trainingstherapie': typeof TrainingstherapieRoute
  '/vortraege': typeof VortraegeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysen': typeof AnalysenRoute
  '/athletiktraining': typeof AthletiktrainingRoute
  '/clubs': typeof ClubsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gruppentraining': typeof GruppentrainingRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/meine-person': typeof MeinePersonRoute
  '/performance-club': typeof PerformanceClubRoute
  '/personaltraining': typeof PersonaltrainingRoute
  '/physiotherapie': typeof PhysiotherapieRoute
  '/start': typeof StartRoute
  '/strength-club': typeof StrengthClubRoute
  '/team': typeof TeamRoute
  '/training-club-widnau': typeof TrainingClubWidnauRoute
  '/training-physio': typeof TrainingPhysioRoute
  '/trainingstherapie': typeof TrainingstherapieRoute
  '/vortraege': typeof VortraegeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysen'
    | '/athletiktraining'
    | '/clubs'
    | '/datenschutz'
    | '/gruppentraining'
    | '/impressum'
    | '/kontakt'
    | '/meine-person'
    | '/performance-club'
    | '/personaltraining'
    | '/physiotherapie'
    | '/start'
    | '/strength-club'
    | '/team'
    | '/training-club-widnau'
    | '/training-physio'
    | '/trainingstherapie'
    | '/vortraege'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysen'
    | '/athletiktraining'
    | '/clubs'
    | '/datenschutz'
    | '/gruppentraining'
    | '/impressum'
    | '/kontakt'
    | '/meine-person'
    | '/performance-club'
    | '/personaltraining'
    | '/physiotherapie'
    | '/start'
    | '/strength-club'
    | '/team'
    | '/training-club-widnau'
    | '/training-physio'
    | '/trainingstherapie'
    | '/vortraege'
  id:
    | '__root__'
    | '/'
    | '/analysen'
    | '/athletiktraining'
    | '/clubs'
    | '/datenschutz'
    | '/gruppentraining'
    | '/impressum'
    | '/kontakt'
    | '/meine-person'
    | '/performance-club'
    | '/personaltraining'
    | '/physiotherapie'
    | '/start'
    | '/strength-club'
    | '/team'
    | '/training-club-widnau'
    | '/training-physio'
    | '/trainingstherapie'
    | '/vortraege'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysenRoute: typeof AnalysenRoute
  AthletiktrainingRoute: typeof AthletiktrainingRoute
  ClubsRoute: typeof ClubsRoute
  DatenschutzRoute: typeof DatenschutzRoute
  GruppentrainingRoute: typeof GruppentrainingRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  MeinePersonRoute: typeof MeinePersonRoute
  PerformanceClubRoute: typeof PerformanceClubRoute
  PersonaltrainingRoute: typeof PersonaltrainingRoute
  PhysiotherapieRoute: typeof PhysiotherapieRoute
  StartRoute: typeof StartRoute
  StrengthClubRoute: typeof StrengthClubRoute
  TeamRoute: typeof TeamRoute
  TrainingClubWidnauRoute: typeof TrainingClubWidnauRoute
  TrainingPhysioRoute: typeof TrainingPhysioRoute
  TrainingstherapieRoute: typeof TrainingstherapieRoute
  VortraegeRoute: typeof VortraegeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysen': {
      id: '/analysen'
      path: '/analysen'
      fullPath: '/analysen'
      preLoaderRoute: typeof AnalysenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletiktraining': {
      id: '/athletiktraining'
      path: '/athletiktraining'
      fullPath: '/athletiktraining'
      preLoaderRoute: typeof AthletiktrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppentraining': {
      id: '/gruppentraining'
      path: '/gruppentraining'
      fullPath: '/gruppentraining'
      preLoaderRoute: typeof GruppentrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meine-person': {
      id: '/meine-person'
      path: '/meine-person'
      fullPath: '/meine-person'
      preLoaderRoute: typeof MeinePersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-club': {
      id: '/performance-club'
      path: '/performance-club'
      fullPath: '/performance-club'
      preLoaderRoute: typeof PerformanceClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personaltraining': {
      id: '/personaltraining'
      path: '/personaltraining'
      fullPath: '/personaltraining'
      preLoaderRoute: typeof PersonaltrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physiotherapie': {
      id: '/physiotherapie'
      path: '/physiotherapie'
      fullPath: '/physiotherapie'
      preLoaderRoute: typeof PhysiotherapieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strength-club': {
      id: '/strength-club'
      path: '/strength-club'
      fullPath: '/strength-club'
      preLoaderRoute: typeof StrengthClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-club-widnau': {
      id: '/training-club-widnau'
      path: '/training-club-widnau'
      fullPath: '/training-club-widnau'
      preLoaderRoute: typeof TrainingClubWidnauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-physio': {
      id: '/training-physio'
      path: '/training-physio'
      fullPath: '/training-physio'
      preLoaderRoute: typeof TrainingPhysioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainingstherapie': {
      id: '/trainingstherapie'
      path: '/trainingstherapie'
      fullPath: '/trainingstherapie'
      preLoaderRoute: typeof TrainingstherapieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vortraege': {
      id: '/vortraege'
      path: '/vortraege'
      fullPath: '/vortraege'
      preLoaderRoute: typeof VortraegeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysenRoute: AnalysenRoute,
  AthletiktrainingRoute: AthletiktrainingRoute,
  ClubsRoute: ClubsRoute,
  DatenschutzRoute: DatenschutzRoute,
  GruppentrainingRoute: GruppentrainingRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  MeinePersonRoute: MeinePersonRoute,
  PerformanceClubRoute: PerformanceClubRoute,
  PersonaltrainingRoute: PersonaltrainingRoute,
  PhysiotherapieRoute: PhysiotherapieRoute,
  StartRoute: StartRoute,
  StrengthClubRoute: StrengthClubRoute,
  TeamRoute: TeamRoute,
  TrainingClubWidnauRoute: TrainingClubWidnauRoute,
  TrainingPhysioRoute: TrainingPhysioRoute,
  TrainingstherapieRoute: TrainingstherapieRoute,
  VortraegeRoute: VortraegeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
